name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        working-directory: prime_visualizer
        run: npm install
      - name: Deploy to GH Pages
        working-directory: prime_visualizer
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/akgupta89/akgupta89.github.io>.git
          npm run deploy
